[package]
name = "rgsp-host"
version = "0.1.0"
edition = "2021"

[lib]
name = "rgsp_host"
path = "src/lib.rs"

[[bin]]
name = "rgsp-host"
path = "src/main.rs"

[dependencies]
moonshine-core = { path = "../vendor/moonshine/moonshine-core" }
rgsp-cedar = { path = "../rgsp-cedar" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "signal", "time", "io-util"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
libc = "0.2"
anyhow = "1"
alsa = "0.9"
async-shutdown = "0.2.2"
toml = "1"
jsonrpsee = { version = "0.26.0", default-features = false, features = ["server", "macros"] }
reth-ipc = { path = "../vendor/reth-ipc" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
jsonrpsee = { version = "0.26.0", default-features = false, features = ["server", "macros", "async-client"] }
